### ISSUE TITLE
Not using UTF-8 file encoding

### ISSUE THREAD

**Issue by yannickpulver** [appswithlove/loco-android#25]
Version `0.2.2` introducted the issue that in some cases, `utf8` is written into the `.xml` files as encoding instead of `utf-8`

![image](https://user-images.githubusercontent.com/827937/141309619-0778a02e-b490-4b91-8c19-c69768342835.png)

**Comment by yannickpulver** [comment]
Should be fixed in `0.2.3`.

**Comment by rasmussl** [comment]
@yannickpulver
I'm testing the plugin (v0.2.3) on 2 different projects.
On one of the projects it get the strings with the `encoding="utf-8"` and in the other project it still gets the strings with `encoding="utf8"`.

**Comment by yannickpulver** [comment]
Hi @rasmussl 
In version `0.2.4` (published just now) I added a fix that replaces the `utf8` encoding with `utf-8` if needed. It should not happen in the first place, but this fix may help to fix lint issues.
